# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: ğŸ™‹  Usage Questions
    url: https://github.com/xmnlab/retsu.git/discussions
    about: |
      Use Retsu's GitHub Discussions to ask "How do I do X with Retsu?".
  - name: ğŸ“–  Tutorial
    url: https://github.com/xmnlab/retsu.git
    about: |
      The Retsu tutorial is continually updated and provides an in depth walkthrough
      of how to use the latest release of Retsu.
  - name: ğŸ“  Retsu Code of Conduct
    url: https://github.com/xmnlab/retsu.git/coc/CODE_OF_CONDUCT.md
    about: Expectations for how people will interact with each other on Retsu's GitHub.
